import React, { createContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    welcome: "Welcome to Fit for Life",
    startJourney: "START YOUR FITNESS JOURNEY NOW! PICK ANY PLAN THAT FITS YOUR LIFE",
    levelUp: "Level up your fitness and health journey with personalized training, fitness technology, and dietitian services.",
    bookPlan: "BOOK A PLAN!",
    yearsExperience: "20+ Years of Experience",
    membersJoined: "100K+ Members Joined",
    annualUsers: "99K+ Annual Users",
    signUpTitle: "LET'S START LIFE TRAINING NOW",
    signUpName: "First and last name",
    signUpPhone: "Phone number",
    signUpEmail: "Email address",
    joinNow: "JOIN NOW!",
    gymInfo1: "GYM 1: Address: GymRoad 24A - Postal Code",
    gymInfo2: "GYM 2: Address: GymRoad 24A - Postal Code",
    gymInfo3: "GYM 3: Address: GymRoad 24A - Postal Code",
    whyChooseUs: "WHY CHOOSE US",
    mobileTeam: "MOBILE TEAM",
    bespokeExperience: "BESPOKE EXPERIENCE",
    advancedTechnology: "ADVANCED TECHNOLOGY",
    satisfactionGuaranteed: "SATISFACTION GUARANTEED",
    professionalTrainers: "OUR PROFESSIONAL TRAINERS",
    trainerBio: "Whether you're looking to set up a home gym or enhance your current workout routine, our professional trainers are here to help you reach your fitness goals.",
    trainerName: "TRAINER_NAME",
    trainerRole: "Role Trainer",
    trainerRating: "★★★★★",
    choosePlan: "CHOOSE YOUR PLAN LEVEL:",
    level1: "LEVEL 1",
    level2: "LEVEL 2",
    level3: "LEVEL 3",
    price: "$price",
    regularPackageAccess: "regular package access",
    yourPlanChoice: "your plan choice",
    fullWeekAccess: "full week access",
    someGymSupplies: "some gym supplies",
    personalLocker: "personal locker",
    dietitianConsultation: "Dietitian Consultation",
    additionalGroupClasses: "additional group classes",
    level1StuffIncluded: "level 1 stuff included",
    fullWorkoutSupplies: "Full workout supplies",
    moreAdvancedSessions: "more advanced sessions",
    personalDietPlan: "Personal diet plan",
    unlimitedAccessToAllServices: "Unlimited access to all services",
    level2Plus1Included: "level 2+1 included",
    close: "Close",
    ourServices: "OUR SERVICES",
    oneMonthSubscription: "1 MONTH SUBSCRIPTION",
    thirtyDaysUnlimitedGym: "30 DAYS OF UNLIMITED GYM USE",
    noTrainer: "NO TRAINER",
    oneMonthSubscriptionTrainer: "1 MONTH SUBSCRIPTION + TRAINER",
    personalTrainer: "Personal trainer",
    scheduledWorkouts: "Scheduled workouts based on your preference",
    sixMonthsSub: "6 MONTHS SUB",
    noCoach: "No coach",
    unlimitedUseGym: "Unlimited use of the gym",
    specialDeals: "Special deals",
    learnMore: "Learn More",
    comparisonTableTitle: "Comparison Table",
    feature: "Feature",
    package1: "Basic Package",
    package2: "Standard Package",
    package3: "Premium Package",
    feature1: "Gym Access",
    feature2: "Support",
    feature3: "Classes",
    testimonialsTitle: "What Our Members Say",
    testimonial1: "This gym has changed my life!",
    testimonialAuthor1: "John Doe",
    testimonial2: "I love the trainers and the community.",
    testimonialAuthor2: "Jane Smith",
    faqsTitle: "Frequently Asked Questions",
    faqQuestion1: "What are the membership fees?",
    faqAnswer1: "Membership fees vary based on the package you choose.",
    faqQuestion2: "Do you offer personal training?",
    faqAnswer2: "Yes, we offer personal training with our Standard and Premium packages.",
    contactUsTitle: "Contact Us",
    contactName: "Name",
    contactEmail: "Email",
    contactMessage: "Message",
    submit: "Submit",
    choose: "Select",
        // Header Translations
        logo: "FIT FOR LIFE",
        ourProcess: "Our Process",
        services: "Services",
        packages: "Packages",
        consultation: "Consultation",
        joinTeam: "Join the Team",
        
        // Packages Page Translations
        packagesTitle: "Our Packages",
        packagesDescription: "Choose the package that best suits your fitness goals.",
        package1Title: "Basic Package",
        package1Feature1: "Access to gym facilities",
        package1Feature2: "Standard support",
        package1Feature3: "Weekly group classes",
        package2Title: "Standard Package",
        package2Feature1: "Personal trainer sessions",
        package2Feature2: "Nutrition consultation",
        package2Feature3: "Daily group classes",
        package3Title: "Premium Package",
        package3Feature1: "All standard features",
        package3Feature2: "Advanced workout plans",
        package3Feature3: "Exclusive access to new facilities",
        initialConsultation: "Initial Consultation",
        initialConsultationDesc: "During the initial consultation, we will discuss your fitness goals, health history, and any concerns you may have. This helps us to understand your needs and tailor a fitness plan specifically for you.",
        fitnessAssessment: "Fitness Assessment",
        fitnessAssessmentDesc: "We conduct a thorough fitness assessment to determine your current fitness level. This includes measuring your strength, flexibility, cardiovascular endurance, and body composition.",
        customizedPlan: "Customized Plan",
        customizedPlanDesc: "Based on the information gathered from the consultation and assessment, we create a customized fitness plan that outlines your workout routine, diet plan, and any necessary lifestyle changes.",
        regularTraining: "Regular Training",
        regularTrainingDesc: "You will begin your training sessions with our certified trainers. These sessions will be tailored to your fitness level and goals, ensuring you get the most out of each workout.",
        progressTracking: "Progress Tracking",
        progressTrackingDesc: "We regularly track your progress and make adjustments to your fitness plan as needed. This ensures that you stay on track and continue to see improvements in your fitness level.",
          //Consulatation translations:
    consultationTitle: "Consultation",
    consultationIntroTitle: "Introduction",
    consultationIntroText: "Welcome to our consultation page. Here you can find all the information you need about our consultation services.",
    consultationTypesTitle: "Types of Consultation",
    consultationType1Title: "Type 1",
    consultationType1Text: "Description of consultation type 1.",
    consultationType2Title: "Type 2",
    consultationType2Text: "Description of consultation type 2.",
    consultationType3Title: "Type 3",
    consultationType3Text: "Description of consultation type 3.",
    consultationBookingTitle: "Book a Consultation",
    namePlaceholder: "Your Name",
    emailPlaceholder: "Your Email",
    phonePlaceholder: "Your Phone Number",
    messagePlaceholder: "Your Message",
    bookNow: "Book Now",
    consultantProfilesTitle: "Our Consultants",
    consultantName1: "Consultant 1",
    consultantBio1: "Bio of consultant 1.",
    consultantName2: "Consultant 2",
    consultantBio2: "Bio of consultant 2.",
    consultantName3: "Consultant 3",
    consultantBio3: "Bio of consultant 3.",
    successStoriesTitle: "Success Stories",
    successStory1: "Story 1",
    successStory2: "Story 2",
    successStory3: "Story 3",
    faqTitle: "Frequently Asked Questions",
    faqQuestion1_1: "Question 1",
    faqAnswer1_1: "Answer 1",
    faqQuestion2_2: "Question 2",
    faqAnswer2_2: "Answer 2",
    faqQuestion3: "Question 3",
    faqAnswer3: "Answer 3",
    contactInfoTitle: "Contact Information",
    contactInfoText: "Here's how you can reach us: <<contact information for the consulting department goes here>>",
      // Join team translations go here
      joinTeamTitle: "Join the Team",
      joinIntroTitle: "Why Join Us?",
      joinIntroText: "We are looking for passionate and dedicated individuals to join our team. If you love fitness and helping others achieve their goals, we want to hear from you!",
      joinBenefitsTitle: "Benefits of Working with Us",
      joinBenefit1: "Competitive salary and benefits",
      joinBenefit2: "Opportunities for growth and development",
      joinBenefit3: "Friendly and supportive work environment",
      openPositionsTitle: "Open Positions",
      position1Title: "Fitness Trainer",
      position1Description: "We are looking for experienced fitness trainers to join our team.",
      position2Title: "Dietitian",
      position2Description: "We are looking for certified dietitians to provide nutritional guidance to our clients.",
      position3Title: "Customer Service Representative",
      position3Description: "We are looking for friendly and professional customer service representatives.",
      applyNow: "Apply Now",
      applyTitle: "Apply Now",
      coverLetterPlaceholder: "Your Cover Letter",
      submitApplication: "Submit Application",   
  },
  uk: {
    welcome: "Ласкаво просимо до Fit for Life",
    startJourney: "ПОЧНІТЬ ВАШ ФІТНЕС ШЛЯХ ЗАРАЗ! ОБЕРІТЬ БУДЬ-ЯКИЙ ПЛАН, ЩО ПІДХОДИТЬ ВАШОМУ ЖИТТЮ",
    levelUp: "Покращуйте ваш фітнес і здоров'я за допомогою персоналізованих тренувань, фітнес-технологій та послуг дієтолога.",
    bookPlan: "ЗАБРОНЮВАТИ ПЛАН!",
    yearsExperience: "20+ років досвіду",
    membersJoined: "100K+ приєднань",
    annualUsers: "99K+ користувачів щороку",
    signUpTitle: "ПОЧНІМО ЖИТТЯ ТРЕНУВАННЯ ЗАРАЗ",
    signUpName: "Ім'я та прізвище",
    signUpPhone: "Номер телефону",
    signUpEmail: "Електронна адреса",
    joinNow: "ПРИЄДНАТИСЯ ЗАРАЗ!",
    gymInfo1: "GYM 1: Адреса: GymRoad 24A - Поштовий індекс",
    gymInfo2: "GYM 2: Адреса: GymRoad 24A - Поштовий індекс",
    gymInfo3: "GYM 3: Адреса: GymRoad 24A - Поштовий індекс",
    whyChooseUs: "ЧОМУ ОБИРАЮТЬ НАС",
    mobileTeam: "МОБІЛЬНА КОМАНДА",
    bespokeExperience: "ІНДИВІДУАЛЬНИЙ ДОСВІД",
    advancedTechnology: "СУЧАСНІ ТЕХНОЛОГІЇ",
    satisfactionGuaranteed: "ГАРАНТІЯ ЗАДОВОЛЕННЯ",
    professionalTrainers: "НАШІ ПРОФЕСІЙНІ ТРЕНЕРИ",
    trainerBio: "Незалежно від того, чи хочете ви створити домашній спортзал або покращити свою поточну програму тренувань, наші професійні тренери допоможуть вам досягти ваших фітнес-цілей.",
    trainerName: "ІМ'Я ТРЕНЕРА",
    trainerRole: "Роль тренера",
    trainerRating: "★★★★★",
    choosePlan: "ОБЕРІТЬ РІВЕНЬ ПЛАНУ:",
    level1: "РІВЕНЬ 1",
    level2: "РІВЕНЬ 2",
    level3: "РІВЕНЬ 3",
    price: "$ціна",
    regularPackageAccess: "доступ до звичайного пакета",
    yourPlanChoice: "ваш вибір плану",
    fullWeekAccess: "доступ на повний тиждень",
    someGymSupplies: "деякі спорттовари",
    personalLocker: "особистий шкафчик",
    dietitianConsultation: "консультація дієтолога",
    additionalGroupClasses: "додаткові групові заняття",
    level1StuffIncluded: "включено речі рівня 1",
    fullWorkoutSupplies: "повний набір спортивного обладнання",
    moreAdvancedSessions: "більше розширених сесій",
    personalDietPlan: "персональний дієтичний план",
    unlimitedAccessToAllServices: "необмежений доступ до всіх послуг",
    level2Plus1Included: "включено рівень 2+1",
    close: "Закрити",
    ourServices: "НАШІ ПОСЛУГИ",
    oneMonthSubscription: "ПІДПИСКА НА 1 МІСЯЦЬ",
    thirtyDaysUnlimitedGym: "30 ДНІВ НЕОБМЕЖЕНОГО ВИКОРИСТАННЯ ТРЕНАЖЕРНОГО ЗАЛУ",
    noTrainer: "БЕЗ ТРЕНЕРА",
    oneMonthSubscriptionTrainer: "ПІДПИСКА НА 1 МІСЯЦЬ + ТРЕНЕР",
    personalTrainer: "Персональний тренер",
    scheduledWorkouts: "Заплановані тренування відповідно до ваших уподобань",
    sixMonthsSub: "ПІДПИСКА НА 6 МІСЯЦІВ",
    noCoach: "Без тренера",
    unlimitedUseGym: "Необмежене використання тренажерного залу",
    specialDeals: "Спеціальні пропозиції",
    choose: "Обрати",
        // Header Translations
        logo: "ФІТНЕС ДЛЯ ЖИТТЯ",
        ourProcess: "Наш процес",
        services: "Послуги",
        packages: "Пакети",
        consultation: "Консультація",
        joinTeam: "Приєднатися до команди",
        
        // Packages Page Translations
        packagesTitle: "Наші пакети",
        packagesDescription: "Виберіть пакет, який найкраще відповідає вашим фітнес-цілям.",
        package1Title: "Базовий пакет",
        package1Feature1: "Доступ до спортивних залів",
        package1Feature2: "Стандартна підтримка",
        package1Feature3: "Щотижневі групові заняття",
        package2Title: "Стандартний пакет",
        package2Feature1: "Сесії з особистим тренером",
        package2Feature2: "Консультація з харчування",
        package2Feature3: "Щоденні групові заняття",
        package3Title: "Преміум пакет",
        package3Feature1: "Усі стандартні функції",
        package3Feature2: "Розширені плани тренувань",
        package3Feature3: "Ексклюзивний доступ до нових об'єктів",
        learnMore: "Дізнатися більше",
        comparisonTableTitle: "Таблиця порівняння",
        feature: "Функція",
        package1: "Базовий пакет",
        package2: "Стандартний пакет",
        package3: "Преміум пакет",
        feature1: "Доступ до спортзалу",
        feature2: "Підтримка",
        feature3: "Заняття",
        testimonialsTitle: "Що кажуть наші партнери",
        testimonial1: "Цей спортзал змінив моє життя!",
        testimonialAuthor1: "Джон Доу",
        testimonial2: "Я люблю тренерів та спільноту.",
        testimonialAuthor2: "Джейн Сміт",
        faqsTitle: "Часті запитання",
        faqQuestion1: "Які внески?",
        faqAnswer1: "Внески залежать від обраного вами пакета.",
        faqQuestion2: "Чи пропонуєте ви особисте тренування?",
        faqAnswer2: "Так, ми пропонуємо особисті тренування з нашими Стандартними та Преміум пакетами.",
        contactUsTitle: "Зв'яжіться з нами",
        contactName: "Ім'я",
        contactEmail: "Електронна пошта",
        contactMessage: "Повідомлення",
        submit: "Надіслати",
        initialConsultation: "Початкова Консультація",
        initialConsultationDesc: "Під час початкової консультації ми обговоримо ваші фітнес-цілі, історію здоров'я та будь-які ваші занепокоєння. Це допомагає нам зрозуміти ваші потреби та розробити фітнес-план спеціально для вас.",
        fitnessAssessment: "Оцінка Фітнесу",
        fitnessAssessmentDesc: "Ми проводимо ретельну оцінку фітнесу, щоб визначити ваш поточний рівень фізичної підготовки. Це включає вимірювання вашої сили, гнучкості, серцево-судинної витривалості та складу тіла.",
        customizedPlan: "Індивідуальний План",
        customizedPlanDesc: "На основі зібраної інформації з консультації та оцінки ми створюємо індивідуальний фітнес-план, що включає ваш режим тренувань, план харчування та необхідні зміни способу життя.",
        regularTraining: "Регулярні Тренування",
        regularTrainingDesc: "Ви розпочнете свої тренування з нашими сертифікованими тренерами. Ці заняття будуть пристосовані до вашого рівня фізичної підготовки та цілей, забезпечуючи максимальну ефективність кожного тренування.",
        progressTracking: "Відстеження Прогресу",
        progressTrackingDesc: "Ми регулярно відстежуємо ваш прогрес і вносимо зміни до вашого фітнес-плану за необхідності. Це гарантує, що ви залишаєтесь на правильному шляху та продовжуєте бачити покращення вашого рівня фізичної підготовки.",
        //consultation translations: 
        consultationTitle: "Консультація",
        consultationIntroTitle: "Вступ",
        consultationIntroText: "Ласкаво просимо на сторінку наших консультацій. Тут ви знайдете всю необхідну інформацію про наші консультаційні послуги.",
        consultationTypesTitle: "Типи Консультацій",
        consultationType1Title: "Тип 1",
        consultationType1Text: "Опис консультації типу 1.",
        consultationType2Title: "Тип 2",
        consultationType2Text: "Опис консультації типу 2.",
        consultationType3Title: "Тип 3",
        consultationType3Text: "Опис консультації типу 3.",
        consultationBookingTitle: "Забронювати Консультацію",
        messagePlaceholder: "Ваше Повідомлення",
        bookNow: "Забронювати",
        consultantProfilesTitle: "Наші Консультанти",
        consultantName1: "Консультант 1",
        consultantBio1: "Біографія консультанта 1.",
        consultantName2: "Консультант 2",
        consultantBio2: "Біографія консультанта 2.",
        consultantName3: "Консультант 3",
        consultantBio3: "Біографія консультанта 3.",
        successStoriesTitle: "Історії Успіху",
        successStory1: "Історія 1",
        successStory2: "Історія 2",
        successStory3: "Історія 3",
        faqTitle: "Часто Задані Питання",
        faqQuestion1_1: "Питання 1",
        faqAnswer1_1: "Відповідь 1",
        faqQuestion2_2: "Питання 2",
        faqAnswer2_2: "Відповідь 2",
        faqQuestion3: "Питання 3",
        faqAnswer3: "Відповідь 3",
        contactInfoTitle: "Контактна Інформація",
        contactInfoText: "Ось як ви можете з нами зв'язатися: <<contact information for the consulting department goes here>>",
        //FIX  DUPE KEYS
         // Join team text goes here
    joinTeamTitle: "Приєднуйтесь до Команди",
    joinIntroTitle: "Чому Обрати Нас?",
    joinIntroText: "Ми шукаємо пристрасних і відданих своїй справі людей для нашої команди. Якщо ви любите фітнес і допомагати іншим досягати їх цілей, ми хочемо почути від вас!",
    joinBenefitsTitle: "Переваги Роботи з Нами",
    joinBenefit1: "Конкурентна зарплата та пільги",
    joinBenefit2: "Можливості для зростання та розвитку",
    joinBenefit3: "Дружнє та підтримуюче робоче середовище",
    openPositionsTitle: "Вакансії",
    position1Title: "Тренер з фітнесу",
    position1Description: "Ми шукаємо досвідчених тренерів з фітнесу для нашої команди.",
    position2Title: "Дієтолог",
    position2Description: "Ми шукаємо сертифікованих дієтологів для надання харчових консультацій нашим клієнтам.",
    position3Title: "Представник служби підтримки",
    position3Description: "Ми шукаємо дружніх і професійних представників служби підтримки.",
    applyNow: "Подати заявку",
    applyTitle: "Подати Заявку",
    namePlaceholder: "Ваше Ім'я",
    emailPlaceholder: "Ваш Email",
    phonePlaceholder: "Ваш Номер Телефону",
    coverLetterPlaceholder: "Ваш Супровідний Лист",
    submitApplication: "Відправити Заявку",
      }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage((prevLang) => (prevLang === 'en' ? 'uk' : 'en'));
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
